image: docker:latest

services:
  - docker:dind

stages:
  - build
  - test
  - release
  - preprod
  - integration
  - prod

docker:
  stage: build
  script:
    - docker build -t django.nv .

safety:
  stage: test
  script:
    - docker run -it --rm -v $PWD:/opt pyupio/safety safety check --file=/opt/requirements.txt --json -o /opt/safety_report.json
  artifacts:
    paths: 
      - safety_report.json
    when: always
  allow_failure: true
    
retirejs:
  stage: test
  script:
    - docker run --rm -v $PWD:/app gruebel/retirejs:latest --outputformat json --outputpath retirejs_report.json
  artifacts:
    paths:
      - retirejs_report.json
    when: always
  allow_failure: true
  
  truffleHog:
    stage: test
    script:
      - docker run -it -v "$PWD:/pwd" ghcr.io/trufflesecurity/trufflehog:latest filesystem --directory="." --debug --json 
    artifacts:
      paths:
        - trufflehog_report.json
      when: always
    allow_failure: true

  
  

    
